SHOW_ENCLOSURE_BOTTOM = true;
SHOW_BATTERY = true;
SHOW_SPEAKER = true;
SHOW_SWITCH = true;
SHOW_PCB = true;
SHOW_VOLUME_WHEEL = true;
SHOW_MOUNTING_RAIL = true;
SHOW_KEYS = true;
SHOW_ENCLOSURE_TOP = true;
SHOW_WINDOW_PANE = false;
SHOW_PENCIL_STAND_PENCIL = false;

USE_PENCIL_STAND_DISPLAY_ANGLE = false;

ANIMATE_VISUALIZED_PLASTIC_TOLERANCE_WEIGHT = false;

QUICK_PREVIEW = true;
CROSS_SECTION = undef;
ECHO_DIMENSIONS = true;
FLIP_VERTICALLY = false;
REDUCED_TEST_CASE = false;
