SHOW_ENCLOSURE_BOTTOM = false;
SHOW_BATTERY = false;
SHOW_SPEAKER = false;
SHOW_SWITCH = false;
SHOW_PCB = false;
SHOW_VOLUME_WHEEL = true;
SHOW_MOUNTING_RAIL = false;
SHOW_KEYS = false;
SHOW_ENCLOSURE_TOP = false;
SHOW_WINDOW_PANE = false;
SHOW_PENCIL_STAND_PENCIL = false;

USE_PENCIL_STAND_DISPLAY_ANGLE = false;

ANIMATE_VISUALIZED_PLASTIC_TOLERANCE_WEIGHT = false;

QUICK_PREVIEW = false;
CROSS_SECTION = undef;
ECHO_DIMENSIONS = true;
FLIP_VERTICALLY = false;
