SHOW_ENCLOSURE_BOTTOM = true;
SHOW_BATTERY = true;
SHOW_SPEAKER = true;
SHOW_SWITCH = true;
SHOW_PCB = true;
SHOW_VOLUME_WHEEL = true;
SHOW_HITCH = true;
SHOW_MOUNTING_RAIL = true;
SHOW_KEYS = true;
SHOW_ENCLOSURE_TOP = true;
SHOW_WINDOW_PANE = false;

ANIMATE_VISUALIZED_PLASTIC_TOLERANCE_WEIGHT = false;

QUICK_PREVIEW = true;
CROSS_SECTION = undef;

ECHO_DIMENSIONS = true;
